
---
# Source: hello-restful/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello-restful
  namespace: demo-dev
  labels:
    app: hello-restful
    version: dev.ed5d3e7
    env: demo-dev
    helm.sh/chart: hello-restful-0.4.0
    app.kubernetes.io/name: hello-restful
    app.kubernetes.io/instance: hello-restful
---
# Source: hello-restful/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: hello-restful
  namespace: demo-dev
  labels:
    app: hello-restful
    version: dev.ed5d3e7
    env: demo-dev
    helm.sh/chart: hello-restful-0.4.0
    app.kubernetes.io/name: hello-restful
    app.kubernetes.io/instance: hello-restful
spec:
  type: ClusterIP
  ports:
    - name: hello-restful
      protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app.kubernetes.io/name: hello-restful
    app.kubernetes.io/instance: hello-restful
---
# Source: hello-restful/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-restful
  namespace: demo-dev
  labels:
    app: hello-restful
    version: dev.ed5d3e7
    env: demo-dev
    helm.sh/chart: hello-restful-0.4.0
    app.kubernetes.io/name: hello-restful
    app.kubernetes.io/instance: hello-restful
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-restful
      app.kubernetes.io/instance: hello-restful
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-restful
        app.kubernetes.io/instance: hello-restful
    spec:
      serviceAccountName: hello-restful
      securityContext:
        {}
      containers:
        - name: hello-restful
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
          image: "ghcr.io/thoughtworks-dps/hello-restful:dev.1c77502"
          imagePullPolicy: IfNotPresent
          ports:
            - name: hello-restful
              containerPort: 8000
              protocol: TCP
          env:
            - name: API_VERSION
              value: dev.ed5d3e7
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /v1/hello/healthz
              port: hello-restful
            initialDelaySeconds: 3
            periodSeconds: 15
            failureThreshold: 4
          readinessProbe:
            httpGet:
              path: /v1/hello/healthz
              port: hello-restful
            initialDelaySeconds: 3
            failureThreshold: 4
            periodSeconds: 15
      nodeSelector:
        kubernetes.io/arch: arm64
      imagePullSecrets:
        - name: regcreds
