{{- if .Values.serviceAccount.create -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  hosts:
    {{- toYaml .Values.virtualService.hosts | nindent 4 }}
  gateways:
    {{- toYaml .Values.virtualService.gateways | nindent 4 }}
  http:
    - route:
      - destination:
          host: {{ include "chart.fullname" . }}
          port:
            number: {{ .Values.service.port | default 80 }}
{{- end }}
