apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-restful.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hello-restful.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "hello-restful.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hello-restful.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "hello-restful.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.service.name | default "http" }}
              containerPort: {{ .Values.service.targetPort | default 80 }}
              protocol: {{ .Values.service.protocol | default "TCP" }}
          env:
            - name: API_VERSION
              value: {{ .Values.image.tag }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /v1/hello/healthz
              port: {{ .Values.service.name | default "http" }}
          readinessProbe:
            httpGet:
              path: /v1/hello/healthz
              port: {{ .Values.service.name | default "http" }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - {{ include "hello-restful.name" . }}
              topologyKey: kubernetes.io/hostname
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: failure-domain.beta.kubernetes.io/zone
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: {{ include "hello-restful.name" . }}
      topologySpreadConstraints:
        - maxSkew: {{ .Values.topologySpreadConstraints.maxZoneSkew }}
          topologyKey: "topology.kubernetes.io/zone"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "hello-restful.name" . }}
        - maxSkew: {{ .Values.topologySpreadConstraints.maxNodeSkew }}
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "hello-restful.name" . }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if ne .Release.Namespace "demo-local" }}
      imagePullSecrets:
        - name: regcreds
      {{- end }}


  
