apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-restful.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hello-restful.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "hello-restful.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hello-restful.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "hello-restful.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.service.name | default "http" }}
              containerPort: {{ .Values.service.targetPort | default 80 }}
              protocol: {{ .Values.service.protocol | default "TCP" }}
          env:
            - name: API_VERSION
              value: {{ .Values.image.tag }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
