{{- if .Values.podDisruptionBudget.create -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "hello-restful.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hello-restful.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "hello-restful.labels" . | nindent 6 }}
{{- end }}
