apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-restful.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hello-restful.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort: {{ .Values.service.targetPort | default "http" }}
      protocol: {{ .Values.service.protocol | default "TCP" }}
      {{- if .Values.service.name }}
      name: {{ .Values.service.name }}
      {{- end }}
  selector:
    {{- include "hello-restful.selectorLabels" . | nindent 4 }}
