apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-restful.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hello-restful.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.name }}
      protocol: {{ .Values.service.protocol | default "TCP" }}
      port: {{ .Values.service.port | default 80 }}
      targetPort: {{ .Values.service.targetPort | default "http" }}
  selector:
    {{- include "hello-restful.selectorLabels" . | nindent 4 }}
