---
version: 2.1

orbs:
  python: twdps/python-api@dev:latest
  cosign: twdps/cosign@dev:latest

# ==== global pipeline parameters

parameters:
  context:
    description: circleci context for all jobs
    type: string
    default: twdps-core-labs-team
  shell-options:
    description: shell options for all jobs
    type: string
    default: op run --env-file op.env -- /bin/bash -eo pipefail
  package-manager:
    description: python package manager
    type: string
    default: pipenv
  registry:
    description: publish to this registry
    type: string
    default: ghcr.io/thoughtworks-dps

  # datadog-version:
  #   description: datadog cli version for all jobs
  #   type: string
  #   default: "0.43.0"

on-push-main: &on-push-main
  branches:
    only: /main/
  tags:
    ignore: /.*/

on-tag-main: &on-tag-main
  branches:
    ignore: /.*/
  tags:
    only: /.*/

workflows:
  version: 2

  development-build:
    jobs:
      # - python/machine-clone-only
      # - python/static-analysis:
      #     name: static-code-analysis
      #     context: << pipeline.parameters.context >>
      #     package-manager: << pipeline.parameters.package-manager >>
      #     lint-path: api
      #     report-coverage: codeclimate
      #     cis-docker-image-scan: true
      #     filters: *on-push-main

      - python/secure-image-build:
          name: secure-build
          context: << pipeline.parameters.context >>
          shell: /bin/bash
          python-version: "3.9.10"
          before-build:
            - run:
                name: inject environment variables
                command: |
                  op inject -i op.env -o $BASH_ENV
                  source $BASH_ENV
                  op inject -i cosign.key.env -o cosign.key
                  op inject -i cosign.pub.env -o cosign.pub
          registry: << pipeline.parameters.registry >>
          image: hello-restful
          image-cve-scan: true
          snyk-organization: twdps
          # cis-docker-image-scan: true
          # health-url: "http://0.0.0.0:8000/v1/hello/healthz/"
          # port-definition: "8000:8000"
          after-push:
            - cosign/install
            - cosign/sign:
                registry: << pipeline.parameters.registry >>
                image: hello-restful
                tag: dev.${CIRCLE_SHA1:0:7}
          # requires:
          #   - static-code-analysis
          filters: *on-push-main
