---
version: 2.1

# ==== global pipeline parameters

parameters:
  context:
    description: circleci context for all jobs
    type: string
    default: twdps-core-labs-team
  shell-options:
    description: shell options for all jobs
    type: string
    default: secrethub run --env-file secrethub.env -- /bin/bash -eo pipefail
  # terraform-version:
  #   description: terraform version for all jobs
  #   type: string
  #   default: "1.1.5"
  # datadog-version:
  #   description: datadog cli version for all jobs
  #   type: string
  #   default: "0.43.0"
  executor-image:
    description: python executor image
    type: string
    default: cimg/python:3.9.11

on-push-main: &on-push-main
  branches:
    only: /main/
  tags:
    ignore: /.*/

on-tag-main: &on-tag-main
  branches:
    ignore: /.*/
  tags:
    only: /.*/

jobs:

  static-analysis:
    docker:
      - image: << pipeline.parameters.executor-image >>
    # shell: << pipeline.parameters.shell-options >>
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install static analysis tools
          command: |
            sudo bash -c "curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > /usr/local/bin/cc-test-reporter"
            sudo chmod +x /usr/local/bin/cc-test-reporter
            pip install pipenv
            PIPENV_VENV_IN_PROJECT=1 pipenv install --dev
            echo "PATH=/.venv/bin:\$PATH" >> $BASH_ENV
      - run:
          name: lint
          command: pipenv run pylint api
      - run:
          name: unit tests
          command: |
            pipenv run coverage run -m pytest -vv -l 
            pipenv run coverage xml --omit='env/*,tests/*'
            cc-test-reporter format-coverage -t coverage.py
            cc-test-reporter upload-coverage


workflows:
  version: 2

  dev-build:
    jobs:
      - static-analysis:
          context: << pipeline.parameters.context >>





