---
version: 2.1

orbs:
  python: twdps/python-api@dev:alpha
  op: twdps/onepassword@3.0.0
  cosign: twdps/cosign@0.1.1
  kube: twdps/kube-ops@1.1.2

globals:
  - &context empc-lab
  - &shell op run --env-file op.env -- /bin/bash -eo pipefail
  - &executor-image twdps/circleci-python-builder:5.0.1
  - &deploy-image twdps/circleci-kube-ops:alpine-3.2.1
  - &package-manager pip
  - &image hello-restful
  - &registry ghcr.io/thoughtworks-dps

on-push-main: &on-push-main
  branches:
    only: /main/
  tags:
    ignore: /.*/

on-tag-main: &on-tag-main
  branches:
    ignore: /.*/
  tags:
    only: /.*/

commands:

  set-environment:
    parameters:
      cluster:
        description: target cluster
        type: string
        default: ""
      tag:
        description: image to deploy
        type: string
        default: dev.${CIRCLE_SHA1:0:7}
    steps:
      - op/env
      - run:
          name: set version var
          command: |
            echo "export API_VERSION=<< parameters.tag >>" >> $BASH_ENV
            source $BASH_ENV
      - op/write-to-file:
          op-value: empc-lab/svc-cosign-private-key/notesPlain
          out-file: cosign.key
      - op/write-to-file:
          op-value: empc-lab/svc-cosign-public-key/notesPlain
          out-file: cosign.pub
      - when:
          condition: << parameters.cluster >>
          steps:
            - kube/op-config:
                op-value: empc-lab/psk-aws-<< parameters.cluster>>/kubeconfig-base64

jobs:

  deploy-hello-restful:
    parameters:
      cluster:
        description: Deploy to cluster role
        type: string
      namespace:
        description: Deploy to environment
        type: string
      tag:
        description: Deploy image version
        type: string
    docker:
      - image: *deploy-image
    steps:
      - checkout
      - setup_remote_docker
      - set-environment:
          cluster: << parameters.cluster >>
          tag: << parameters.tag >>
      - run:
          name: deploy hello-restful
          command: bash scripts/deploy.sh << parameters.namespace >> << parameters.tag >>
      - run:
          name: test healthz endpoint
          command: bash scripts/healthz_check.sh << parameters.namespace >> << parameters.tag >>
      - run:
          name: TODO - Deploy observability dashboard, monitoring, and alerting
          command: echo "Placeholder for observability deployment"

workflows:
  version: 2

  development-build:
    jobs:
      - python/static-analysis:
          name: static code analysis
          context: *context
          shell: *shell
          executor-image: *executor-image
          package-manager: *package-manager
          install-dev: true
          lint-path: api
          report-coverage: codacy
          after-checkout:
            - run:
                name: set API_VERSION
                command: |
                  echo "export API_VERSION=dev.${CIRCLE_SHA1:0:7}" >> $BASH_ENV
                  source $BASH_ENV
          filters: *on-push-main

      - python/oci-image-build:
          name: build multi-arch image
          context: *context
          image: *image
          registry: *registry
          cve-scan: true
          snyk-organization: twdps
          health-url: "http://0.0.0.0:8000/v1/hello/healthz"
          port-definition: "8000:8000"
          docker-run-arguments: "-e API_VERSION=dev.${CIRCLE_SHA1:0:7}"
          before-build:
            - set-environment
          requires:
            - static code analysis
          filters: *on-push-main

      - deploy-hello-restful:
          name: dev deployment
          context: *context
          cluster: prod-i01-aws-us-east-2
          namespace: dev
          tag: dev.${CIRCLE_SHA1:0:7}
          requires:
            - build multi-arch image
          filters: *on-push-main

  release:
    jobs:
      - python/publish-image:
          name: publish release candidate
          context: *context
          image: *image
          registry: *registry
          publish-tag: $CIRCLE_TAG
          before-push:
            - set-environment
          filters: *on-tag-main

      - deploy-hello-restful:
          name: qa deployment
          context: *context
          cluster: prod-i01-aws-us-east-2
          namespace: qa
          tag: $CIRCLE_TAG
          requires:
            - publish release candidate
          filters: *on-tag-main

      - deploy-hello-restful:
          name: preview deployment
          context: *context
          cluster: sbx-i01-aws-us-east-1
          namespace: preview
          tag: $CIRCLE_TAG
          requires:
            - publish release candidate
          filters: *on-tag-main

      - approve-prod:
          type: approval
          requires:
            - qa deployment
          filters: *on-tag-main

      - deploy-hello-restful:
          name: prod deployment
          context: *context
          cluster: prod-i01-aws-us-east-2
          namespace: prod
          tag: $CIRCLE_TAG
          requires:
            - approve-prod
          filters: *on-tag-main
