---
version: 2.1

orbs:
  python: twdps/python-api@dev:latest

# ==== global pipeline parameters

parameters:
  context:
    description: circleci context for all jobs
    type: string
    default: twdps-core-labs-team
  shell-options:
    description: shell options for all jobs
    type: string
    default: secrethub run --env-file secrethub.env -- /bin/bash -eo pipefail
  virtualenv:
    description: python virtual env method
    type: string
    default: pipenv
  # datadog-version:
  #   description: datadog cli version for all jobs
  #   type: string
  #   default: "0.43.0"
  # executor-image:
  #   description: python executor image
  #   type: string
  #   default: cimg/python:3.9.11

on-push-main: &on-push-main
  branches:
    only: /main/
  tags:
    ignore: /.*/

on-tag-main: &on-tag-main
  branches:
    ignore: /.*/
  tags:
    only: /.*/

# jobs:

#  build-image:

workflows:
  version: 2

  dev-build:
    jobs:
      # - python/clone-only
      - python/static-analysis:
          context: << pipeline.parameters.context >>
          virtualenv: << pipeline.parameters.virtualenv >>
          lint-path: api
          report-coverage: codeclimate
          cis-docker-image-scan: true

      # - build-image:
      #     context: << pipeline.parameters.context >>
