nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""
  annotations: {}

service:
  type: ClusterIP
  portname: http
  port: 80
  protocol: TCP
  targetPort: 8000

virtualService:
  create: true
  hosts:
    - dev.twdps.io
  gateways:
    - istio-system/dev-twdps-io-gateway
  matchUrl: /v1/hello

image:
  repository: ghcr.io/thoughtworks-dps
  name: hello-restful
  tag: ""
  pullPolicy: IfNotPresent

podSecurityContext: {}

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  utilizationMethod: memory
  targetUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
