# values.yaml includes prod settings

virtualService:
  create: true
  hosts:
    - api.twdps.io
  gateways:
    - istio-system/api-twdps-io-gateway
  matchUrl: /v1/hello

image:
  pullPolicy: Always

resources:
  limits:
    cpu: 200m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  utilizationMethod: memory
  targetUtilizationPercentage: 80

podDisruptionBudget:
  maxUnavailable: 1

# affinity:
#   podAntiAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       - labelSelector:
#           matchExpressions:
#             - key: app.kubernetes.io/name
#               operator: In
#               values:
#                 - hello-restful
#         topologyKey: kubernetes.io/hostname
#     preferredDuringSchedulingIgnoredDuringExecution:
#       - weight: 100
#         podAffinityTerm:
#           topologyKey: failure-domain.beta.kubernetes.io/zone
#           labelSelector:
#             matchLabels:
#               app.kubernetes.io/name: hello-restful

# topologySpreadConstraints:
#   - maxSkew: 1
#     topologyKey: "topology.kubernetes.io/zone"
#     whenUnsatisfiable: ScheduleAnyway
#     labelSelector:
#       matchLabels:
#         app.kubernetes.io/name: hello-restful
#   - maxSkew: 1
#     topologyKey: "kubernetes.io/hostname"
#     whenUnsatisfiable: ScheduleAnyway
#     labelSelector:
#       matchLabels:
#         app.kubernetes.io/name: hello-restful
