nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""
  annotations: {}

service:
  name: hello-restful
  type: ClusterIP
  portname: hello-restful
  port: 80
  protocol: TCP
  targetPort: 8000

virtualService:
  create: false
  # hosts:
  #   - "example.com"
  # gateways:
  #   - istio-system/example-com-gateway
  # matchUrl: /v1/hello

image:
  repository: ghcr.io/thoughtworks-dps
  name: hello-restful
  tag: ""
  pullPolicy: IfNotPresent

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 100%
    maxUnavailable: 50%

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop: ["ALL"]

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# required for podDisruptionBudget
autoscaling:
  enabled: false
  # minReplicas: 1
  # maxReplicas: 3
  # utilizationMethod: memory
  # targetUtilizationPercentage: 80

affinity: {}

nodeSelector:
  kubernetes.io/arch: arm64

tolerations: []

topologySpreadConstraints: {}

podDisruptionBudget: 
  create: false
  # maxUnavailable: 1
