# values.yaml includes prod settings

virtualService:
  create: true
  hosts:
    - twdps.io
  gateways:
    - istio-system/prod-twdps-io-gateway
  matchUrl: /v1/hello

image:
  pullPolicy: Always

resources:
  limits:
    cpu: 200m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 3
  maxReplicas: 5

podDisruptionBudget:
  maxUnavailable: 2