# values.yaml includes dev settings

virtualService:
  create: true
  hosts:
    - dev.twdps.io
  gateways:
    - istio-system/dev-twdps-io-gateway
  matchUrl: /v1/hello

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  utilizationMethod: memory
  targetUtilizationPercentage: 80

podDisruptionBudget: 
  create: true
  maxUnavailable: 1
